name: polymerfts
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cmake=3.31
  - pybind11=2.13
  - numpy=2.2
  - scipy=1.14
  - pandas=2.3
  - matplotlib=3.10
  - spglib=2.5
  - make
  - git
  - pip
  - openmpi
  - pyyaml
  - jupyter
  - networkx
  - pygraphviz
  - pygments
  - plotly
  - nbformat
